spring:
  application:
    name: Local Hobbies Backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/local_hobbies}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate #let Flyway change tables
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  jackson:
    mapper:
      accept-case-insensitive-enums: true #for java.time.DayOfWeek

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  user:
    onboarding:
      min-num-hobbies: ${ONBOARDING_MIN_NUM_HOBBIES:3}
      min-num-availabilities: ${ONBOARDING_MIN_NUM_AVAILABILITIES:1}
  availability:
    #time window within which an availability can be scheduled; also time window
    #within which recurring availabilities are projected to intervals
    scheduling-window-days: ${AVAILABILITY_SCHEDULING_WINDOW_DAYS:180}
    #time window within which users' schedules are compared
    overlap-window-days: ${AVAILABILITY_OVERLAP_WINDOW_DAYS:30}
    #maximum duration of an availability
    max-duration-hours: ${AVAILABILITY_MAX_DURATION_HOURS:168}

logging:
  level:
    root: info
    org.flywaydb: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug
    io.github.csci499_group8: debug
